/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tabungan;


import java.awt.Color;
import java.awt.Frame;
import java.awt.geom.RoundRectangle2D;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author riogesta
 */
public class Beranda extends javax.swing.JFrame {

    /**
     * Creates new form Beranda
     */
    
    public String title;
    
    static boolean maximized = true;
    int Xmouse;
    int Ymouse;
    
    DefaultTableModel model_penabung;
    public Beranda() {
        
        // Rounded UI
        //setLayout(null);
        setUndecorated(true);
        //setSize(400,300);
        setLocationRelativeTo(null);
        setShape(new RoundRectangle2D.Double(0,0, 700,480, 15,15));
        // end-Rounded UI

        initComponents();
        // percantik
        lineAmbilTabungan.setVisible(false);
        lineNabung.setVisible(false);
        lineTambahPenabung.setVisible(false);
        
        //
        String [] title_tb_penabung = {"Kode", "Nama", "Jenis Kelamin", "No.Telepon", "Alamat"};
        model_penabung = new DefaultTableModel(title_tb_penabung,0);
        tbPenabung.setModel(model_penabung);
        
        showDataPenabung();
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu = new javax.swing.JPanel();
        lblTambahPenabung = new javax.swing.JLabel();
        lblNabung = new javax.swing.JLabel();
        lblAmbilTabungan = new javax.swing.JLabel();
        lineAmbilTabungan = new javax.swing.JPanel();
        lineNabung = new javax.swing.JPanel();
        lineTambahPenabung = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPenabung = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        panelDraggable = new javax.swing.JPanel();
        btnExit = new javax.swing.JLabel();
        btnHide = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tabungan");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTambahPenabung.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 13)); // NOI18N
        lblTambahPenabung.setText("Tambah Penabung");
        lblTambahPenabung.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblTambahPenabung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTambahPenabungMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblTambahPenabungMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblTambahPenabungMouseExited(evt);
            }
        });
        panelMenu.add(lblTambahPenabung, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 10, -1, -1));

        lblNabung.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 13)); // NOI18N
        lblNabung.setText("Nabung");
        lblNabung.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblNabung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNabungMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblNabungMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblNabungMouseExited(evt);
            }
        });
        panelMenu.add(lblNabung, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, -1, -1));

        lblAmbilTabungan.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 13)); // NOI18N
        lblAmbilTabungan.setText("Ambil Tabungan");
        lblAmbilTabungan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblAmbilTabungan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAmbilTabunganMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAmbilTabunganMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAmbilTabunganMouseExited(evt);
            }
        });
        panelMenu.add(lblAmbilTabungan, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, -1, -1));

        lineAmbilTabungan.setBackground(new java.awt.Color(38, 78, 112));

        javax.swing.GroupLayout lineAmbilTabunganLayout = new javax.swing.GroupLayout(lineAmbilTabungan);
        lineAmbilTabungan.setLayout(lineAmbilTabunganLayout);
        lineAmbilTabunganLayout.setHorizontalGroup(
            lineAmbilTabunganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        lineAmbilTabunganLayout.setVerticalGroup(
            lineAmbilTabunganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        panelMenu.add(lineAmbilTabungan, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 34, 120, 3));

        lineNabung.setBackground(new java.awt.Color(38, 78, 112));

        javax.swing.GroupLayout lineNabungLayout = new javax.swing.GroupLayout(lineNabung);
        lineNabung.setLayout(lineNabungLayout);
        lineNabungLayout.setHorizontalGroup(
            lineNabungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
        );
        lineNabungLayout.setVerticalGroup(
            lineNabungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        panelMenu.add(lineNabung, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 34, 55, 3));

        lineTambahPenabung.setBackground(new java.awt.Color(38, 78, 112));

        javax.swing.GroupLayout lineTambahPenabungLayout = new javax.swing.GroupLayout(lineTambahPenabung);
        lineTambahPenabung.setLayout(lineTambahPenabungLayout);
        lineTambahPenabungLayout.setHorizontalGroup(
            lineTambahPenabungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        lineTambahPenabungLayout.setVerticalGroup(
            lineTambahPenabungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelMenu.add(lineTambahPenabung, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 34, 130, 3));

        getContentPane().add(panelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 419, 700, 60));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbPenabung.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tbPenabung.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbPenabung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPenabungMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbPenabung);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 64, 650, 310));

        jLabel3.setFont(new java.awt.Font("Lucida Sans Unicode", 2, 13)); // NOI18N
        jLabel3.setText("Daftar Penabung : ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 700, 400));

        panelDraggable.setBackground(new java.awt.Color(38, 78, 112));
        panelDraggable.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelDraggableMouseDragged(evt);
            }
        });
        panelDraggable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelDraggableMousePressed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(38, 78, 112));
        btnExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close.png"))); // NOI18N
        btnExit.setOpaque(true);
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });

        btnHide.setBackground(new java.awt.Color(38, 78, 112));
        btnHide.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnHide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/minus (1).png"))); // NOI18N
        btnHide.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnHide.setOpaque(true);
        btnHide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHideMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHideMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHideMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tabungan");

        javax.swing.GroupLayout panelDraggableLayout = new javax.swing.GroupLayout(panelDraggable);
        panelDraggable.setLayout(panelDraggableLayout);
        panelDraggableLayout.setHorizontalGroup(
            panelDraggableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDraggableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 564, Short.MAX_VALUE)
                .addComponent(btnHide, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelDraggableLayout.setVerticalGroup(
            panelDraggableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
            .addComponent(btnHide, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(panelDraggable, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblTambahPenabungMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTambahPenabungMouseClicked
        // TODO add your handling code here:
        new tambahPenabung().setVisible(true);
        dispose();
    }//GEN-LAST:event_lblTambahPenabungMouseClicked

    private void lblNabungMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNabungMouseClicked
        // TODO add your handling code here:
        new Nabung().setVisible(true);
        dispose();
    }//GEN-LAST:event_lblNabungMouseClicked

    private void lblAmbilTabunganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAmbilTabunganMouseClicked
        // TODO add your handling code here:
        new ambilTabungan().setVisible(true);
        dispose();
    }//GEN-LAST:event_lblAmbilTabunganMouseClicked

    private void panelDraggableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDraggableMousePressed
        // TODO add your handling code here:
        Xmouse =  evt.getX();
        Ymouse =  evt.getY();
    }//GEN-LAST:event_panelDraggableMousePressed

    private void panelDraggableMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDraggableMouseDragged
        // TODO add your handling code here:
        if(maximized){
            int x = evt.getXOnScreen();
            int y = evt.getYOnScreen();
            this.setLocation(x - Xmouse, y - Ymouse);
        }
    }//GEN-LAST:event_panelDraggableMouseDragged

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnHideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHideMouseClicked
        // TODO add your handling code here:
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_btnHideMouseClicked

    private void tbPenabungMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPenabungMouseClicked
        // TODO add your handling code here:
        int i = tbPenabung.getSelectedRow();
        infoPenabung ip = new infoPenabung();
        
        if(i > -1){
            
            ip.setVisible(true); ip.pack();
            //ip.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            
            ip.tfKodePenabung.setText(model_penabung.getValueAt(i, 0).toString());
            ip.tfNamaPenabung.setText(model_penabung.getValueAt(i, 1).toString());
            String jk = model_penabung.getValueAt(i, 2).toString();
            String kode = model_penabung.getValueAt(i, 0).toString();
            ip.cbJenisKelamin.setSelectedItem(jk);
            
            ip.getKodePenabung(kode);
            
            ip.tfNoTelp.setText(model_penabung.getValueAt(i, 3).toString());
            ip.taAlamat.setText(model_penabung.getValueAt(i, 4).toString());
            
            this.dispose();
        }
        
        
    }//GEN-LAST:event_tbPenabungMouseClicked

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        // TODO add your handling code here:
        btnExit.setBackground(new Color(232, 17, 35));
    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        // TODO add your handling code here:
        btnExit.setBackground(new Color(38,78,112));
    }//GEN-LAST:event_btnExitMouseExited

    private void lblAmbilTabunganMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAmbilTabunganMouseEntered
        // TODO add your handling code here:
        lineAmbilTabungan.setVisible(true);
    }//GEN-LAST:event_lblAmbilTabunganMouseEntered

    private void lblAmbilTabunganMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAmbilTabunganMouseExited
        // TODO add your handling code here:
        lineAmbilTabungan.setVisible(false);
    }//GEN-LAST:event_lblAmbilTabunganMouseExited

    private void lblNabungMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNabungMouseEntered
        // TODO add your handling code here:
        lineNabung.setVisible(true);
    }//GEN-LAST:event_lblNabungMouseEntered

    private void lblNabungMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNabungMouseExited
        // TODO add your handling code here:
        lineNabung.setVisible(false);
    }//GEN-LAST:event_lblNabungMouseExited

    private void lblTambahPenabungMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTambahPenabungMouseEntered
        // TODO add your handling code here:
        lineTambahPenabung.setVisible(true);
    }//GEN-LAST:event_lblTambahPenabungMouseEntered

    private void lblTambahPenabungMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTambahPenabungMouseExited
        // TODO add your handling code here:
        lineTambahPenabung.setVisible(false);
    }//GEN-LAST:event_lblTambahPenabungMouseExited

    private void btnHideMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHideMouseEntered
        // TODO add your handling code here:
        btnHide.setBackground(new Color(18, 43, 64));
    }//GEN-LAST:event_btnHideMouseEntered

    private void btnHideMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHideMouseExited
        // TODO add your handling code here:
        btnHide.setBackground(new Color(38,78,112));
    }//GEN-LAST:event_btnHideMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Beranda().setVisible(true);
            }
        });
    }
    
    public void showDataPenabung(){
        
        
        int row = model_penabung.getRowCount();
        for(int i = 0 ; i < row ; i++){
            model_penabung.removeRow(0);
        }
        
        int no = 1;
        try {
            Connection cn = (Connection) tabungan.Conn_db.mysqlconn();
            ResultSet rs = cn.createStatement().executeQuery("select * from tb_penabung");
            
            while(rs.next()){
                //String data [] = {rs.getString,rs.getString(1),rs.getString(2),rs.getString(3)};
                model_penabung.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4), rs.getString(5)});
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "kesalahan\n"+ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnExit;
    private javax.swing.JLabel btnHide;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAmbilTabungan;
    private javax.swing.JLabel lblNabung;
    private javax.swing.JLabel lblTambahPenabung;
    private javax.swing.JPanel lineAmbilTabungan;
    private javax.swing.JPanel lineNabung;
    private javax.swing.JPanel lineTambahPenabung;
    private javax.swing.JPanel panelDraggable;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JTable tbPenabung;
    // End of variables declaration//GEN-END:variables
}
